######################################################################
# Automatically generated by qmake (3.0) Sun Nov 6 15:54:21 2016
######################################################################

TEMPLATE = app
TARGET = src
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h tentang.h
FORMS += mainwindow.ui tentang.ui
SOURCES += main.cpp mainwindow.cpp tentang.cpp
RESOURCES += resource.qrc
